// # OQUE É WEBSOCKET
//> UMA APLICAÇÃO TCP QUE ESCUTA UMA PORTA DE UM SERVIDOR QUE SEGUE UM PROTOCOLO ESPECIFICO
//> ESTABELECE UMA CONEXAO COM O NAVEGADOR E SE COMUNICA DIRETAMENTE COM ELE
//> DEFINE UM CANAL DE COUMICAÇÃO FULL-DUPLEX ATRAVES DE UM UNICO SOCKET ATRAVES DA WEB EM TEMPO REAL TANTO CLIENTE COMO SERVIDOR
//> A CONEXAO É ESTABELECIDA UMA UNICA VEZ E A COMUNICAÇÃO ENTRE O SERVIDOR E O NAVEGADOR SE TORNA CONTINUA
//> USADO EM APLICAÇÕES QUE REQUEREM ATUALIZAÇÕES REGURARES E RAPIDAS A PARTIR DE UM WEBSERVER(JOGOS MULTIPLAYER, CHAT, ETC)

// # ANTIGAMENTE ESSA COMUNICAÇÃO ERA FEITA DE DUAS FORMAS
// # POOLING: UTILIZAVA DUAS TECNICAS (SHORT E LONG POOLING)
//> O CLIENTE FAZ REQUEISIÇÕES EM BUSCA DE NOVOS DADOS REGULARMENTE
//> PODE SER FEITO DE DUAS MANEIRAS: SHORT POLLING E LONG POLLING
//--> SHORT POOLING
//>REQUISIÇÕES AJAX FEITAS EM INTERVALOS DE TEMPO FIXOS
//--> LONG POOLING
//> MANTEM A CONEXAO HTTP ABERTA ATE O SERVIDOR TER DADOS DISPONIVEIS PARA PASSAR PARA O CLIENTE

// # SOCKET.IO
//> OFERECE UMA API SIMPLES BASEADA EM EVENTOS 
//> PERMITE A COMUNICAÇÃO ENTRE O SERVIDOR E O CLIENTE EM TEMPO REAL
//> FOI DESENVOLVIDO EM JS E FUNCIONA TANTO NO FRONTEND QUANTO NO BACKEND(NODE)
//> O MECANISMO PADRAO É O WEBSOCKETS, COM FALLBACKS EM FLASH E AJAX